version: '3.8'

services:
  cms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cms-application
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/api/content"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
